# general
seed: 1
device: 'cuda'
output_path: 'PNP-results/horse'
attn_t: 0.5
f_t: 0.8
sd_version: '2.1'
guidance_scale: 7.5

# data
image_path: '/content/stones.jpg'     #input the path of your image
latents_path: 'latents_forward'           #The main folder where latens are saved

# Inference
n_timesteps: 50
prompt:  A woman standing
negative_prompt: unrealistic


